library(ggplot2)
library(questionr)
library(dplyr)
library(ggmap)
library(readr)
library(lubridate)
library(magrittr)
library(leaflet)
library(rCharts)

setwd("/Users/admin/Desktop/Master_DEsiGEO/EcoleDesPonts/TP_Data/SanFransisco_data/Shiny")
data <- read_csv2("data3.csv")
name <- sort(unique(data$Name))
dayofweek <- sort(unique(data$DayOfWeek))
